# Generated by Django 2.2.1 on 2019-05-08 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Required', max_length=10)),
                ('age', models.IntegerField(help_text='Required, must be between 0 and 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('profession', models.CharField(blank=True, help_text='Who is reading a help text anyway?', max_length=50, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StandInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('lon', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('accuracy', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('entwicklungsstufe', models.CharField(choices=[('JW', 'Jungwuchs'), ('SH', 'Stangenholz'), ('BH', 'Baumholz'), ('ST', 'Stufig')], max_length=2)),
                ('mischungsgrad', models.FloatField(default=0, help_text='Mischungsgrad Nadelholz [0-100%]', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bemerkungen', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['webm', 'mpg', 'ogg', 'mp4', 'm4p', 'm4v'])], verbose_name='')),
            ],
        ),
    ]
