# Generated by Django 2.2.1 on 2019-05-22 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestcollector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standinformation',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
