# Generated by Django 2.2.1 on 2019-05-23 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forestcollector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standinformation',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
